### PR TITLE
Add standard healthchecks and heartbeat

### PR DESCRIPTION
**Pull request by RMcVelia**
## Description

Add standard service healthchecks and heartbeat
Update application probe_path to /ping

## Trello Card Link

https://trello.com/c/

### CODE REVIEW

**Review by thomasleese — COMMENTED** [review]
As this is a Rails app you might want to use the (fairly popular) [OkComputer](https://github.com/sportngin/okcomputer/#performing-checks) Gem as an alternative to having to write the health checks yourself.

https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/46 is how we did this on Apply for QTS.

**Review by smneal — APPROVED** [review]

**Comment by raul-gracia** [comment]
I agree with @thomasleese that using the gem makes the code a bit cleaner, and if it has already been used before on different project and its the standard way, we should replicate it.

**Comment by padv2010** [comment]
@RMcVelia we have created #110 as suggested by @thomasleese. If you are happy with it, can you please merge it?
Thanks @thomasleese and sorry for the slow reply

**Comment by thomasleese** [comment]
@thomasleese. If you are happy with it, can you please merge it?

I don't have permission to merge it unfortunately (my approve doesn't count) - but I'm not actually super familiar with the repo, so probably best to get someone else to!

**Pull request closed without merging**
